trigger:
- main

variables:
  docker_image_name: 'production/image-base-python'
  docker_registry: 'labvix.azurecr.io'
  docker_registry_account: 'labvix'

pool:
 name: Default
 demands:
   - Agent.OS -equals Linux 
   
steps:
- task: Docker@2
  displayName: 'Build and Publish Docker Image'
  inputs:
    containerRegistry: '$(docker_registry_account)'
    repository: '$(docker_image_name)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
