trigger:
- main

variables:
  docker_registry: 'labvix.azurecr.io'
  docker_registry_account: 'dockerTESTE'
   
steps:
- task: Docker@2
  displayName: 'Build and Publish Docker Image'
  inputs:
    containerRegistry: '$(docker_registry_account)'
    repository: '$(docker_registry)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
